name: snaprent
description: "SnapRent is a real estate platform that connects property owners and tenants using a token-based viewing model and a monthly listing cycle."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.1
  google_maps_flutter: ^2.12.3
  permission_handler: ^11.0.1
  location: ^7.0.1
  flutter_map: ^6.1.0
  flutter_map_marker_popup: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  app_settings: ^5.0.0+2
  timeago: ^3.3.0
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^7.1.1
  image_picker: ^0.8.7+5
  http_parser: ^4.0.2
  mime: ^1.0.2
  video_player: ^2.5.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.4.1
  restart_app: ^1.3.2
  dropdown_search: ^6.0.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # intl_generator: ^0.20.2
  flutter_launcher_icons: ^0.13.1
  intl_utils: ^2.8.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/test/
    - assets/marker_icons/
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo/app_icon.png"
  min_sdk_android: 21
